spring.datasource.url=jdbc:postgressql://localhost:5432/users
spring.datasource.username=sachin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Set this to Postgres to ensure correct sequence handling
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update